# Generated by Django 5.1.5 on 2025-02-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation_document', '0002_feasibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Feasibility',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
